---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: Install Unbound and necessary packages
  apt:
    name:
      - unbound
      - wget
    state: present

- name: Ensure Unbound configuration directory exists
  file:
    path: "{{ unbound_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download root hints file
  get_url:
    url: "{{ root_hints_url }}"
    dest: "{{ unbound_config_dir }}/root.hints"
    mode: '0644'
    owner: root
    group: root
  notify: Restart Unbound

- name: Configure Unbound using template
  template:
    src: templates/unbound.conf.j2
    dest: "{{ unbound_config_dir }}/unbound.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Unbound

- name: Ensure Unbound service is enabled and started
  systemd:
    name: unbound
    enabled: yes
    state: started
