---
- name: Load variables from vault
  include_vars: homelab_vault.yml
  
- name: Ensure Pi-hole configuration directory exists
  file:
    path: "{{ pihole_volume }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure dnsmasq configuration directory exists
  file:
    path: "{{ dnsmasq_volume }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Pi-hole environment variables
  template:
    src: templates/pihole.setupvars.j2
    dest: "{{ pihole_volume }}/pihole.env"
    owner: root
    group: root
    mode: '0644'

- name: Configure dnsmasq settings
  template:
    src: templates/dnsmasq.extras.j2
    dest: "{{ dnsmasq_volume }}/10-custom.conf"
    owner: root
    group: root
    mode: '0644'

- name: Configure Pi-hole to use host's Unbound as DNS server
  lineinfile:
    path: "{{ pihole_volume }}/pihole.env"
    regexp: '^DNS1='
    line: "DNS1={{ unbound_host_ip }}#{{ unbound_port }}"
  notify: Restart Pi-hole

- name: Deploy Pi-hole container
  community.docker.docker_container:
    name: "{{ pihole_container_name }}"
    image: "{{ pihole_image }}"
    state: started
    restart_policy: always
    hostname: "{{ internal_domain }}"
    ports: "{{ container_ports }}"
    network_mode: host
    env_file: "{{ pihole_volume }}/pihole.env"
    volumes:
      - "{{ pihole_volume }}:/etc/pihole"
      - "{{ dnsmasq_volume }}:/etc/dnsmasq.d"

- name: Adjust rate-limiting in Pi-hole
  lineinfile:
    path: "{{ pihole_volume }}/pihole-FTL.conf"
    line: "RATE_LIMIT={{ rate_limit }}"
    create: yes
    state: present

- name: Increase dns-forward-max in Pi-hole
  lineinfile:
    path: "{{ dnsmasq_volume }}/99-dnsmasq.conf"
    line: "dns-forward-max={{ dns_forward_max }}"
    create: yes
    state: present

- name: Configure EDNS buffer size
  lineinfile:
    path: "{{ dnsmasq_volume }}/99-edns.conf"
    line: "edns-packet-max=1232"
    create: yes
    state: present

- name: Clear custom DNS records
  command: 'docker exec {{ pihole_container_name }} bash -c "echo > /etc/pihole/custom.list"'
  changed_when: true

- name: Add custom DNS records for Pi-hole
  shell: |
    echo "{{ item.ip }} {{ item.name }}" >> /etc/pihole/custom.list
  args:
    executable: /bin/bash
  loop: "{{ local_dns_records }}"
  register: dns_addition

- name: Add custom blacklist to Pi-hole
  command: >
    docker exec {{ pihole_container_name }}
    pihole -a adlist add {{ stevenblack_hosts_url }}
  changed_when: false

- name: Update Pi-hole Gravity
  command: docker exec {{ pihole_container_name }} pihole -g
  changed_when: false