---
- name: Install Pihole & Unbound
  hosts: link, zelda
  become: true
  tasks:

- name: Update and Upgrade All Packages
  import_playbook: update_packages.yml

- name: Install Dependencies for Managing Pi-hole
  import_playbook: install_dependencies.yml

- name: Install Unbound
  import_playbook: install_unbound.yml

- name: Install and Configure Pi-hole
  import_playbook: install_pihole.yml
