---
- name: Install Docker-based Pi-hole and Unbound
  hosts: zelda
  become: true

  tasks:
- name: Install and configure Docker environment
  import_playbook: install_docker.yml

- name: Deploy Unbound Docker container
  import_playbook: deploy_unbound_docker.yml

- name: Deploy Pi-hole Docker container
  import_playbook: deploy_pihole_docker.yml
