---
- name: Install Unbound
  hosts: link, zelda
  become: true
  tasks:
    - name: Install Unbound
      ansible.builtin.apt:
        name: unbound
        state: latest

    - name: Configure Unbound
      blockinfile:
        path: /etc/unbound/unbound.conf.d/pi-hole.conf
        block: |
          server:
            do-ip6: no
            port: 5335
            interface: 0.0.0.0
            access-control: 127.0.0.0/8 allow
            access-control: 192.168.0.0/16 allow
            private-address: 192.168.0.0/16
            do-tcp: yes
            hide-identity: yes
            hide-version: yes
            harden-glue: yes
            harden-dnssec-stripped: yes
            use-caps-for-id: yes
            cache-min-ttl: 3600
            cache-max-ttl: 86400
            prefetch: yes
            num-threads: 4
            msg-cache-slabs: 4
            rrset-cache-slabs: 4
            infra-cache-slabs: 4
            key-cache-slabs: 4
            rrset-cache-size: 256m
            msg-cache-size: 128m
            so-rcvbuf: 1m
            so-sndbuf: 1m
            so-reuseport: yes
            minimal-responses: yes
            module-config: "validator iterator"
        create: yes
        backup: yes

    - name: Restart Unbound to apply configuration
      ansible.builtin.systemd:
        name: unbound
        state: restarted
        enabled: yes
