---
- name: Install Docker-based Pi-hole and Unbound on Link
  hosts: link
  become: true

  roles:
    - update_pi_packages
    - install_docker
    - install_unbound
    - install_pihole
    - install_glances
