---
- name: Install Docker-based Pi-hole and Unbound on Zelda
  import_playbook: zelda.yml

- name: Install Docker-based Pi-hole and Unbound on Link
  import_playbook: link.yml

- name: Update Cloudflare DNS
  import_playbook: update_cloudflare_dns.yml
