---
- name: Install Docker-based Pi-hole and Unbound on Zelda
  hosts: zelda
  become: true

  roles:
    - update_pi_packages
    - install_docker
    - install_unbound
    - install_pihole
    - install_glances
