---
- name: Install Docker-based Pi-hole and Unbound
  hosts: zelda
  become: true

  roles:
    - update_pi_packages
    - install_docker

  tasks:

- name: Deploy Unbound Docker container
  import_playbook: deploy_unbound_docker.yml

- name: Deploy Pi-hole Docker container
  import_playbook: install_pihole.yml

- name: Deploy Telegraf Container
  import_playbook: telegraf.yml
