---
- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - dnsutils  # Existing package
      - lm-sensors  # Added package to monitor system sensors
    state: present
