---
# tasks file for roles/update_pi_packages
- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Install dnsutils package
  ansible.builtin.apt:
    name: dnsutils
    state: present
